"""Edit username

Revision ID: 368636d49de4
Revises: 26adffe17708
Create Date: 2021-03-03 12:17:27.061706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368636d49de4'
down_revision = '26adffe17708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('kudos', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('profile_blurb', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('sticker_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'stickers', ['sticker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sticker_id')
    op.drop_column('users', 'profile_blurb')
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'kudos')
    op.drop_column('users', 'joined_date')
    # ### end Alembic commands ###
